services:
  - type: web
    name: medcom-site
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: true
      - key: SESSION_DRIVER
        value: file
      - key: APP_URL
        value: https://medcom-site.onrender.com
      - key: APP_KEY
        value: base64:rU2n8lfYgwG9dlnFiW1eZTT8ncSO29nB3Z/OxkjxTZ0=
