services:
  - type: web
    name: medcom-site
    runtime: php
    buildCommand: composer install
    startCommand: php artisan serve --host 0.0.0.0 --port 10000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: true
      - key: SESSION_DRIVER
        value: file
      - key: APP_URL
        value: https://medcom-site.onrender.com
      - key: APP_KEY
        value: base64:rU2n8lfYgwG9dlnFiW1eZTT8ncSO29nB3Z/OxkjxTZ0=
